name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 3.107.211.240
          username: ubuntu
          key: ${{ secrets.SSH_SECRET_KEY }}
          port: 22
          script_path: script.sh